var readline= require('readline');
var utility = require('../Functionalprograms/Utility/utility.js');
var read = readline.createInterface({
    input:process.stdin,
    output:process.stdout
});
/******************************************************************************
 *  Execution       :   1. default node         cmd> node FlipCoin.js 
 *                      
 * 
 *  Purpose         : Determines the percentage of heads and tails is generated.
 * 
 *  @description    : It takes input of the number of times the coin should be tossed and for each time the head or tails coming is counted, percentage of heads and tail is being calculated and shown as output.
 * 
 *  @file           : FlipCoin.js
 *  @overview       : FlipCoin module to calculate the percentage of heads and tail generated by a random number.
 *  @module         : Random
 *  @author         : Upamanyu
 *  @version        : 1.0
 *  @since          : 06-08-2017
 *
 ******************************************************************************/
function Random()
{
    read.question("Enter the number of times to flip the coin: ", function(t){
    utility.Random(t);
    read.close();
    })
}
Random();